version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: gnharishkumar/reverseproxy:"$VERSION"
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: gnharishkumar/udacity-restapi-user:"$VERSION"
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed
    image: gnharishkumar/udacity-restapi-feed:"$VERSION"
  frontend:
    build:
      context: ../../udacity-c3-frontend
    image: gnharishkumar/udacity-frontend:local
